spring:
  application:
    name: order-management
  profiles:
    active: local
DATASOURCE:
  URL: jdbc:mysql://localhost:3306/testes
  DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
  POOL_NAME: order-management
  CONNECTION_TIMEOUT: 60000
  MAX_POOL_SIZE: 3
DATASOURCE_USERNAME: 'root'
DATASOURCE_PASSWORD: 'root'
